refFasta_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.pc_transcripts.fa.gz'
sampleFile: 'sampleTable1106.tab'
salmon_version: 'salmon/0.11.0'
sratoolkit_version: 'sratoolkit/2.9.2'
refGTF_pa_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.primary_assembly.annotation.gtf.gz'
refGTF_basic_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/gencode.v28.basic.annotation.gtf.gz'
refPA_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_28/GRCh38.primary_assembly.genome.fa.gz'
synth_body: 'ref/synth_body.txt'
tx_not_in_gtf: 'ref/tx_not_in_gtf'
