refFasta_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.transcripts.fa.gz'
sampleFile: '/data/swamyvs/EiaD_build/sampleTable_20201028_thompson_download_successful.tsv'
salmon_version: 'salmon/1.4.0'
R_version: 'R/3.5.0'
samtools_version: 'samtools/1.9'
scripts_dir: '/data/swamyvs/EiaD_build/scripts'
sratoolkit_version: 'sratoolkit/2.9.2'
refGTF_pa_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.primary_assembly.annotation.gtf.gz'
refGTF_basic_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gtf.gz'
refPA_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/GRCh38.primary_assembly.genome.fa.gz'
synth_body: 'ref/synth_body.txt'
tx_not_in_gtf: 'ref/tx_not_in_gtf'
working_dir: '/data/swamyvs/EiaD_build'
sqlfile: 'ref/SRAmetadb.11-06-18.sqlite'
salmon_index_path: '/data/swamyvs/EiaD_build/ref/salmonindexTrimmed'
raw_salmon_index: '/data/swamyvs/EiaD_build/ref/salmonindex'
build_new_salmon_index: 'YES'
download_fastq: 'NO'
EiaD_sqlite_file: 'results/EiaD_human_expression_2020_12.sqlite'
fastqPart_path: '/data/swamyvs/EiaD_build'
fastq_file_path: '/data/OGVFB_BG/EiaD_2019_05'
