refFasta_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.transcripts.fa.gz'
sampleFile: '/home/mcgaugheyd/git/autoRNAseq/sampleTable1128_tissues.tab'
salmon_version: 'salmon/0.11.0'
scripts_dir: '/home/mcgaugheyd/git/autoRNAseq/scripts'
sratoolkit_version: 'sratoolkit/2.9.2'
refGTF_pa_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.primary_assembly.annotation.gtf.gz'
refGTF_basic_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gtf.gz'
refPA_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/GRCh38.primary_assembly.genome.fa.gz'
synth_body: 'ref/synth_body.txt'
tx_not_in_gtf: 'ref/tx_not_in_gtf'
working_dir: '/data/mcgaugheyd/projects/nei/mcgaughey/auto_eyeIntegration'
sqlfile: 'ref/SRAmetadb.11-06-18.sqlite' 
