sample_fastq_table: '/home/mcgaugheyd/git/EiaD_build/data/2023_09_01_snakemake_input.tsv'
fastq_dir: '/data/OGVFB_BG/EiaD_fastq'
ftp: 'rsync://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_'
gencode_version: '44'
genome: 'GRCh38.primary_assembly.genome.fa.gz'
annotation_path: 'reference/'
fq1_suffix: "_1.fastq.gz"
fq2_suffix: "_2.fastq.gz"
fqS_suffix: '.fastq.gz'
R_make_counts_path: '/home/mcgaugheyd/git/EiaD_build/scripts/make_counts.R'
