refFasta_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.transcripts.fa.gz'
sampleFile: '/home/mcgaugheyd/git/autoRNAseq/sampleTable_2019-02-14_tissues.tab'
salmon_version: 'salmon/0.11.0'
R_version: 'R/3.5.0'
samtools_version: 'samtools/1.9'
scripts_dir: '/home/mcgaugheyd/git/autoRNAseq/scripts'
sratoolkit_version: 'sratoolkit/2.9.2'
refGTF_pa_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.primary_assembly.annotation.gtf.gz'
refGTF_basic_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/gencode.v29.annotation.gtf.gz'
refPA_url: 'ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_29/GRCh38.primary_assembly.genome.fa.gz'
synth_body: 'ref/synth_body.txt'
tx_not_in_gtf: 'ref/tx_not_in_gtf'
working_dir: '/data/mcgaugheyd/projects/nei/mcgaughey/auto_eyeIntegration'
sqlfile: 'ref/SRAmetadb.11-06-18.sqlite'
salmon_index_path: 'ref/salmonindexTrimmed'
build_new_salmon_index: 'NO'
download_fastq: 'NO'
EiaD_sqlite_file: 'results/EiaD_human_expression_2019_02.sqlite'
